In [1]:
import numpy as np
import math

def cholesky(A):
    n = len(A)
    L = np.zeros((n, n))

    for i in range(n):
        for j in range(i + 1):
            soma = sum(L[i][k] * L[j][k] for k in range(j))

            if i == j: # Elementos da diagonal
                val = A[i][i] - soma
                if val <= 0:
                    raise ValueError("A matriz não é positiva definida.")
                L[i][j] = math.sqrt(val)
            else: # Elementos abaixo da diagonal
                L[i][j] = (1.0 / L[j][j] * (A[i][j] - soma))
    return L

def substituicao_progressiva(L, b):
    # Resolve o sistema L * y = b
    n = len(b)
    y = np.zeros(n)
    for i in range(n):
        soma = sum(L[i][j] * y[j] for j in range(i))
        y[i] = (b[i] - soma) / L[i][i]
    return y

def substituicao_regressiva(U, y):
    #Resolve o sistema U * x = y (onde U = L.T)
    n = len(y)
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        soma = sum(U[i][j] * x[j] for j in range(i + 1, n))
        x[i] = (y[i] - soma) / U[i][i]
    return x

#  DADOS DO PROBLEMA
A = np.array([
    [4.0, 2.0, -2.0],
    [2.0, 2.0, -1.0],
    [-2.0, -1.0, 5.0]
])

# Vetor b
b = np.array([0.0, 3.0, -7.0])

# EXECUÇÃO
print("1. Matriz A:")
print(A)

# Decomposição
L = cholesky(A)
print("\n2. Matriz L (Decomposição):")
print(L)

# Resolver Ly = b
y = substituicao_progressiva(L, b)
print("\n3. Vetor y (Solução intermediária):")
print(y)

# Resolver L.T x = y
x = substituicao_regressiva(L.T, y)
print("\n4. Vetor x (Solução Final):")
print(x)

#  VERIFICAÇÃO
print("\n Verificação (A * x) ")
print(np.dot(A, x))
print(f"Deve ser igual a b: {b}")
if np.dot(A, x).all() == b.all():
    print("Passou na prova real!")
else:
    print("Não Passou na prova real!")

1. Matriz A:
[[ 4.  2. -2.]
 [ 2.  2. -1.]
 [-2. -1.  5.]]

2. Matriz L (Decomposição):
[[ 2.  0.  0.]
 [ 1.  1.  0.]
 [-1.  0.  2.]]

3. Vetor y (Solução intermediária):
[ 0.   3.  -3.5]

4. Vetor x (Solução Final):
[-2.375  3.    -1.75 ]

 Verificação (A * x) 
[ 0.  3. -7.]
Deve ser igual a b: [ 0.  3. -7.]
Passou na prova real!
