Uma barra está presa por 3 molas que exercem força quando comprimidas. As

---

constantes elásticas são:

k₁ = 100 N/m

k₂ = 50 N/m

k₃ = 80 N/m

k₄ = 70 N/m

Forças aplicadas:

F₁ = 500 N

F₂ = 0

F₃ = 0

In [9]:
import numpy as np
import math

def cholesky(A):
    n = len(A)
    L = np.zeros((n, n))

    for i in range(n):
        for j in range(i + 1):
            soma = sum(L[i][k] * L[j][k] for k in range(j))

            if i == j:
                val = A[i][i] - soma
                if val <= 0:
                    raise ValueError("A matriz não é positiva definida.")
                L[i][j] = math.sqrt(val)
            else:
                L[i][j] = (A[i][j] - soma) / L[j][j]
    return L

def substituicao_progressiva(L, b):
    n = len(b)
    y = np.zeros(n)
    for i in range(n):
        soma = sum(L[i][j] * y[j] for j in range(i))
        y[i] = (b[i] - soma) / L[i][i]
    return y

def substituicao_regressiva(U, y):
    n = len(y)
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        soma = sum(U[i][j] * x[j] for j in range(i + 1, n))
        x[i] = (y[i] - soma) / U[i][i]
    return x

#    DADOS DO PROBLEMA DAS MOLAS

k1 = 100
k2 = 50
k3 = 80
k4 = 70

# Matriz de rigidez
A = np.array([
    [k1 + k2,   -k2,       0       ],
    [ -k2,    k2 + k3,    -k3     ],
    [   0,      -k3,    k3 + k4   ]
], dtype=float)

# Vetor de forças
b = np.array([500.0, 0.0, 0.0])

# Execução do método de Cholesky

print("1. Matriz de rigidez A:")
print(A)

L = cholesky(A)
print("\n2. Matriz L (Cholesky):")
print(np.round(L, 2))

y = substituicao_progressiva(L, b)
print("\n3. Vetor y:")
print(np.round(y, 2))

x = substituicao_regressiva(L.T, y)
print("\n4. Deslocamentos x (solução final):")
print(np.round(x, 2))

# Verificação
print("\nVerificação A*x:")
print(np.dot(A, x))
print("Vetor b:", np.round(b, 2))


1. Matriz de rigidez A:
[[150. -50.   0.]
 [-50. 130. -80.]
 [  0. -80. 150.]]

2. Matriz L (Cholesky):
[[12.25  0.    0.  ]
 [-4.08 10.65  0.  ]
 [ 0.   -7.51  9.67]]

3. Vetor y:
[40.82 15.66 12.16]

4. Deslocamentos x (solução final):
[4.12 2.36 1.26]

Verificação A*x:
[5.00000000e+02 6.75015599e-14 3.50830476e-14]
Vetor b: [500.   0.   0.]
